inputs:
  bump-type:
    description: Example value that can be passed and checked against
    default: patch

runs:
  using: "composite"
  steps:
      - name: Say hello
        shell: bash
        run: |
          echo "Hello Everyone"

      - name: Run on major or minor only
        shell: bash
        # if: contains(fromJson('["major", "minor"]'), github.event.inputs.bump-version)
        run: |
          echo "Hello major/minor"

      - name: Run on patch
        shell: bash
        # if: github.event.inputs.bump-version == 'patch'
        run: |
          echo "Hello patch"

      - name: Run on everything except skip
        shell: bash
        # if: github.event.inputs.bump-version != 'skip'
        run: |
          echo "Hello not skip"

      - name: Debug stuffs
        shell: bash
        run: |
          echo "${{ contains(fromJson('["major", "minor"]'), inputs.bump-type) }}"
          echo "${{ inputs.bump-type == 'major' }}"
          echo "${{ inputs.bump-type == 'minor' }}"
          echo "${{ inputs.bump-type == 'patch' }}"
          echo "${{ inputs.bump-type != 'skip' }}"
