inputs:
  bump-type:
    description: Example value that can be passed and checked against
    default: patch

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
      - name: Say hello
        shell: bash
        run: |
          echo "Hello Everyone"

      - name: Run on major or minor only
        shell: bash
        # if: contains(fromJson('["major", "minor"]'), github.event.inputs.bump-version)
        run: |
          if [ "${{ contains(fromJson('["major", "minor"]'), inputs.bump-type) }}" = "true" ]; then
            echo "Hello major/minor"
          fi

      - name: Run on patch
        shell: bash
        # if: github.event.inputs.bump-version == 'patch'
        run: |
          if [ "${{ inputs.bump-type == 'patch' }}" = "true" ]; then
            echo "Hello patch"
          fi

      - name: Run on everything except skip
        shell: bash
        # if: github.event.inputs.bump-version != 'skip'
        run: |
          if [ "${{ inputs.bump-type }}" != "skip" ]; then
            echo "Hello not skip"
          fi

    - id: random-number-generator
      shell: bash
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
