inputs:
  bump-type:
    description: Example value that can be passed and checked against
    default: patch

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
      - name: Say hello
        shell: bash
        run: |
          echo "Hello Everyone bump-type=${{ github.event.inputs.bump-version }}"

      - name: Run on major or minor only
        shell: bash
        if: contains(fromJson('["major", "minor"]'), github.event.inputs.bump-version)
        run: |
          echo "Hello major/minor"

      - name: Run on patch
        shell: bash
        if: github.event.inputs.bump-version == 'patch'
        run: |
          echo "Hello patch"

      - name: Run on everything except skip
        shell: bash
        if: github.event.inputs.bump-version != 'skip'
        run: |
          echo "Hello not skip"

      - id: random-number-generator
        shell: bash
        run: echo "::set-output name=random-id::$(echo $RANDOM)"
