# This script is used to test running commands within a docker container
#
# Test the run with gh cli:
#
#   gh workflow run docker_shell
name: contains

on:
  workflow_dispatch:
    inputs:
      bump-version:
        description: "Bump version request"
        default: patch

jobs:
  docker_execute:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: cat ${{ github.event_path }}

      - name: Debug the input
        run: echo "${{ github.event.inputs.app_name }}"

      - name: Run on major or minor only
        if: contains(fromJson('["major", "minor"]'), github.event.inputs.bump-version)
        run: echo "Hello World"

      - name: Run on patch
        if: github.event.inputs.bump-version == "patch"
        run: echo "Hello World"

      - name: Run on everything except skip
        if: github.event.inputs.bump-version != "skip"
        run: echo "Hello World"
