# What happens when a cron is triggered and inputs exist in a dispatch
name: crons_share

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: An app name of course!
  # Turn this on when you want to test, I don't want to waste my free actions
  # schedule:
  #   - cron:  '*/5 * * * *'

env:
  # If a default was needed you can do this
  DEFAULT_APP_NAME: 'default-app'

jobs:
  simple_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: cat ${{ github.event_path }}

      - name: Test the input
        run: echo "${{ github.event.inputs.app-name || env.DEFAULT_APP_NAME }}"

      - name: Get last PR author
        id: get_author
        run: |
          # Add "::set-output " to start of the echo below to actually set the output
          echo "name=author::$(gh --repo ${{ github.event.repository.clone_url }} pr view $(gh --repo ${{ github.event.repository.clone_url }} pr list -s merged | head -n1 | awk '{print $1}') | grep 'author:' | awk '{print $2}')"
