# Test the run with:
#   gh workflow run dispatch_release.yaml --json << EOF
#   {"app_name": "test-app", "tag": "v1.2.3"}
#   EOF
name: dispatch_release

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: The name of the application.
        required: true
      tag:
        description: The semver image tag to use.
        required: true


jobs:
  python_execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apps repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update overlay with image [kustomize]
        shell: python
        env:
          APP_NAME: ${{ inputs.app_name }}
          TAG: ${{ inputs.tag }}
        run: |
          import os
          print(f"Hello {os.environ['APP_NAME']}:{os.environ['TAG']}")
