# This script is used to test running commands within a docker container
#
# Test the run with gh cli:
#
#   gh workflow run docker_shell
name: docker_shell

on:
  workflow_dispatch:

jobs:
  docker_execute:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: cat ${{ github.event_path }}

      - id: extract_workspace
        run: echo "::set-output name=workspace::${{ github.workspace }}"

      - name: Test docker
        shell: docker run --rm -v {0}:/run_cmd.sh -v ${{ steps.extract_workspace.outputs.workspace}}:/code alpine sh run_cmd.sh
        run: |
          # Test if we can run multiple commands
          echo "Hello World"
          ls -al

          # Jump to the workspace directory and see if there is anything in the file
          cd /code
          ls -al
