# This script is used to test running commands within a docker container
#
# Test the run with gh cli:
#
#   gh workflow run docker_shell
name: docker_shell

on:
  workflow_dispatch:

jobs:
  docker_execute:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: cat ${{ github.event_path }}

      - id: extract_workspace
        run: echo "${{ github.workspace }}"

      # Note: It looks like you can use the variable interpellation in the shell line (so the path must be hardcoded)
      - name: Test docker
        shell: docker run --rm -v {0}:/run_cmd.sh -v /home/runner/work/action-playground/action-playground:/code alpine sh run_cmd.sh
        run: |
          # Test if we can run multiple commands
          echo "Hello World"
          ls -al

          # Jump to the workspace directory and see if there is anything in the file
          cd /code
          ls -al
