# This script is used to test how to use the contains function in the condition check
#
# Test the run with gh cli:
#
#   gh workflow run trigger_call
name: trigger_call

on:
  workflow_dispatch:
    inputs:
      request-error:
        description: "Pass an error down"
        default: false

jobs:
  sample:
    uses: KyleJamesWalker/action-playground/.github/workflows/workflow_call_test.yml@main
    with:
      request-error: ${{ github.event.inputs.request-error }}
