# This script is use to see how referencing a workflow call works
#
# Test the run with gh cli:
#
#   gh workflow run trigger_call
name: trigger_call

on:
  workflow_dispatch:
    inputs:
      request-error:
        description: Pass an error down
        default: 'false'

jobs:
  sample:
    uses: KyleJamesWalker/action-playground/.github/workflows/workflow_call_test.yaml@master
    with:
      request-error: ${{ github.event.inputs.request-error }}
