on:
  workflow_call:
    inputs:
      request-error:
        description: Error the job when passed at true
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  sub_call:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: cat ${{ github.event_path }}

      - name: Simple Message
        run: |
          if [ "${{ inputs.request-error }}" = "true" ]; then
            exit 1
          else
            echo "Hello world"
          fi
